# Generated by Django 5.0.6 on 2024-05-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_users_borrowedbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userPassword',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
